steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'helloWorld', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'helloWorld']
